# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Package

on:
 push:
   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 安装node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name : 安装依赖
        run  : npm install 
   
      - name : 构建
        run : npm run pkg

